# Dockerfile.logging
FROM node:24.14.0-alpine3.22 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build logging-service

FROM node:24.14.0-alpine3.22
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
CMD ["node", "dist/apps/logging-service/main"]